#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

exit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuxJ"
    "REFUOI2lkt9vU2UYxz/vOW9/2LVzGytlP8zqNIKaSBQdhh9qFENCjGjirRdeKDcGjdFE46UR"
    "B02md+qliWJEcJjFEsLF1BCYM8WtujkqG2OuW7seymA9p+3pec/rxWb5A/jePcmTz/N9vs8j"
    "tNbciSTAd0KgAQV4sE2axluxZN/BaF9fp+95lK9dKxeWltN2w/tUwZ+1jd5PtF4H/C8Fh3oH"
    "dgxtPXw4suXZ57AKBfwVi7j2EvmfR18bHz796nRu9kNgaH3WhgO9Xh3a9spLXzz2+ZfIzs3c"
    "WljganYK5daRgQDJnbvovrtdxr4/cfTXP7IAxwCE1pqvhXioa+cTmadHRsIynqA8OUl1fh4d"
    "j6MBZ3iYFq2J+ZrIzTLfnDmjssvFgSGtLxkAQog3H3zn7bCMJ7hy6hTzmQz58XGE52G4LqV8"
    "Hmv7dq7MzaKKFru6e0xpGh8AGACx3sTLCbfEjdGz+IbJ/fv2QX4RGg2EUujFRZJ79tD++hvM"
    "/ZVF+jXaotHnmxlEurs2+emTFK6useX0OayTJ+jZFEeGw2CadFVsikcH6T2W4mJbB5F/54gF"
    "ZLQJ8H1NvVJFhINo10X9Poahfep/XwY02rlFbWwMVXUIJpPUc1OocOT2H6yWV2/U771ns5kv"
    "Yba34VllFs6mUed+xGuAfd2mY/deZLQVXSyihcGq23CaGZTyhbRlRJHXV3DPXyDx8SCBRA+1"
    "ZRvHsmnp6KQ/laI+M40zeQnnrhBLtfovzTOmhHgk+fDWzO774rKSW6LrhzQqFsEeHkErReuL"
    "LxAIBpk4cID6/D/8huFPrtl7j2t9wdjYIzszdfn9zFKFQGcLhYP7cY9/S8uOR4k9OUD1pxGm"
    "n3mKxmyOnCGZWLOPSLjYdPCZENggHXi3v7/vyAPRoGhdsZDKx/cUa3aVUiDAjDCYqDiDGj4K"
    "gfOV1rcBDuAAVXjcDIXe6wiH9ofwo0opVpV2VhqN0ZueShlwXgABoAm4E/0H1sFjF4s/XVsA"
    "AAAASUVORK5CYII=")

# vim: ts=4:sw=4:et:sts=4:ai:tw=80
